version: '3'

services:
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
     - wordpress_files:/var/www/html
     ports:
     - "8000-8090:80"
     restart: always
     env_file: 
     - env_wordpress
     networks:
     - app-network
   db:
     image: mysql:5.7
     volumes:
     - db_data:/var/lib/mysql
     restart: always
     env_file: 
     - env_db
     networks:
     - app-network
volumes:
  wordpress_files:
  db_data:
networks:
  app-network:
